version: '{build}'

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "true"

before_build:
  - set PATH=%MINGW%\bin;%QT5%\bin;%SystemRoot%\system32;%PATH%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
  - mkdir .\build
  - cd .\build

    cmake --version && cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
