dist: xenial
sudo: required
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-xenial
  - travis_retry sudo apt-get update
  - travis_wait 30 sudo apt-get -y install -qq mesa-common-dev qt510-meta-full qt510charts-no-lgpl

script:
  - source /opt/qt510/bin/qt10-env.sh 
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DEBIAN=ON
  - make -j4